### PR TITLE
Support Rails 5.1

### PR DESCRIPTION
**Pull request by joelmichael**
Requires calling to_i when doing multiplication or division on Durations.

### CODE REVIEW

**Comment by joelmichael** [comment]
ping @radar

**Comment by radar** [comment]
I can confirm this issue fixes compatibility with Rails 5.1. I am setting up appraisal to run the test suite across multiple Rails versions before I merge this PR.

**Comment by joelmichael** [comment]
Thx!

**Comment by radar** [comment]
I'll be doing a new 4.0.0 release soon which will include this change.

**Pull request merged**
