### PR TITLE
Add support for weeks

### PR DESCRIPTION
**Pull request by lauranjansen**
Fixes issue #61 

  Added support for weeks in the time hash
  Added new tests
  Adjusted existing tests

### CODE REVIEW

**Comment by lauranjansen** [comment]
Could you perhaps look at this bundler issue to see if that fixes the build error?
https://github.com/bundler/bundler/issues/3558

**Comment by lauranjansen** [comment]
Ok, fixed the tests by updating the `travis.yml` file. Could someone else review the code as well before I merge it?

@redbar0n? @rvenk?

**Comment by redbar0n** [comment]
I looked at the code in the commit and what is there looks good to me. I don't know enough about the codebase in general to say if anything is missing.

**Comment by lauranjansen** [comment]
Thanks for taking a look!

However, because it changes the existing functionality (:highest_measure_only will now display weeks between days and months), I'm considering not merging this PR until I figure out how to bump the major version. Do you think that would be ok?

**Comment by redbar0n** [comment]
Yeah. You could probably submit a PR to change the readme as well, so it
corresponds. And notify @radar about it so he or someone else can include
accept it in the major version.

**Pull request merged**
